spring:
  application:
    name: ubbl-data-service
  devtools:
    restart:
      enabled: true
    add-properties: true

logging:
  level:
    org.springframework.boot.autoconfigure.logging: INFO

---
spring:
  profiles: dev
server:
  port: 8081
---

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    instanceId: ${DOMAIN_NAME}
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI}
      
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 600000
  ConnectTimeout: 10000